version: '3.5'

services:

    traefik:
        image: traefik:alpine
        container_name: traefik
        restart: always
        ports:
          - 80:80
          - 443:443
        networks:
          - web
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${TRAEFIK_TOML}:/traefik.toml
          - ${ACME_JSON}:/acme.json

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        restart: always
        user: '1000:1000'
        networks:
            - web
            - default
        expose:
            - 8096
        volumes:
            - '${JELLYFIN_CONFIG}:/config'
            - '${JELLYFIN_CACHE}:/cache'
            - '${MEDIA}:/media'
        labels:
            - 'traefik.backend=jellyfin'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=8096'

    cloud-torrent:
        image: jpillora/cloud-torrent
        container_name: cloud-torrent
        restart: always
        user: '1000:1000'
        networks:
            - web
            - default
        expose:
            - 3000
        volumes:
            - '${MEDIA}:/downloads'
        labels:
            - 'traefik.backend=cloud-torrent'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:torrent.${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=3000'
        command:
            --auth ${AUTH}

    gohttpserver:
        image: codeskyblue/gohttpserver
        container_name: gohttpserver
        restart: always
        user: '1000:1000'
        networks:
            - web
            - default
        expose:
            - 8000
        volumes:
            - '${MEDIA}:/app/public'
        labels:
            - 'traefik.backend=gohttpserver'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:files.${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=8000'
        command:
            --auth-type http
            --auth-http ${AUTH}
            --upload
    
    netdata:
        image: netdata/netdata
        container_name: netdata
        restart: always
        hostname: monitor.dopeflix.xyz # set to fqdn of host
        ports:
          - 19999:19999
        cap_add:
          - SYS_PTRACE
        security_opt:
          - apparmor:unconfined
        volumes:
          - /etc/passwd:/host/etc/passwd:ro
          - /etc/group:/host/etc/group:ro
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro   
        labels:
            - 'traefik.backend=netdata'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:monitor.${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=19999'  
 
networks:
    web:
        external: true
