version: '3.5'

services:
    gohttpserver:
        image: codeskyblue/gohttpserver
        container_name: gohttpserver
        restart: always
        networks:
            - web
            - default
        expose:
            - 8000
        volumes:
            - '${MEDIA}:/app/public'
        labels:
            - 'traefik.backend=gohttpserver'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:files.${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=8000'
        command:
            --auth-type http
            --auth-http ${AUTH}

    cloud-torrent:
        image: jpillora/cloud-torrent
        container_name: cloud-torrent
        restart: always
        networks:
            - web
            - default
        expose:
            - 3000
        volumes:
            - '${MEDIA}:/downloads'
        labels:
            - 'traefik.backend=cloud-torrent'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:torrent.${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=3000'
        command:
            --auth ${AUTH}

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        restart: always
        networks:
            - web
            - default
        expose:
            - 8096
        volumes:
            - '${JELLYFIN_CONFIG}:/config'
            - '${JELLYFIN_CACHE}:/cache'
            - '${MEDIA}:/media'
        labels:
            - 'traefik.backend=jellyfin'
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:${URL}'
            - 'traefik.docker.network=web'
            - 'traefik.port=8096'
 
networks:
    web:
        external: true
