version: '3.5'

services:
    gohttpserver:
        image: codeskyblue/gohttpserver
        container_name: gohttpserver
        restart: unless-stopped
        network_mode: "host"
        volumes:
            - '${MEDIA}:/app/public'
        command:
            --auth-type http
            --auth-http ${AUTH}

    cloud-torrent:
        image: jpillora/cloud-torrent
        container_name: cloud-torrent
        restart: unless-stopped
        network_mode: "host"
        volumes:
            - '${MEDIA}:/downloads'
        command:
            --auth ${AUTH}

    jellyfin:
        image: jellyfin/jellyfin
        container_name: jellyfin
        restart: unless-stopped
        network_mode: "host"
        volumes:
            - '${JELLYFIN_CONFIG}:/config'
            - '${JELLYFIN_CACHE}:/cache'
            - '${MEDIA}:/media'
