version: '3.5'

services:
    gohttpserver:
        image: codeskyblue/gohttpserver
        container_name: gohttpserver
        restart: unless-stopped
        network_mode: "host"
        volumes:
            - '${HOME}:/app/public'
        command:
            --auth-type http
            --auth-http ${AUTH}

    cloud-torrent:
        image: jpillora/cloud-torrent
        container_name: cloud-torrent
        restart: unless-stopped
        network_mode: "host"
        volumes:
            - '${DOWNLOADS}:/downloads'
        command:
            --auth ${AUTH}
